/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Client.Api;
using Domain.Api.V2.Client.Model;
using Domain.Api.V2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListingsV2ListingMedia
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingsV2ListingMediaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingsV2ListingMedia
        //private ListingsV2ListingMedia instance;

        public ListingsV2ListingMediaTests()
        {
            // TODO uncomment below to create an instance of ListingsV2ListingMedia
            //instance = new ListingsV2ListingMedia();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingsV2ListingMedia
        /// </summary>
        [Fact]
        public void ListingsV2ListingMediaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingsV2ListingMedia
            //Assert.IsType<ListingsV2ListingMedia>(instance);
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
