/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Client.Api;
using Domain.Api.V2.Client.Model;
using Domain.Api.V2.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PreMarketV1ListingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreMarketV1ListingRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreMarketV1ListingRequest
        //private PreMarketV1ListingRequest instance;

        public PreMarketV1ListingRequestTests()
        {
            // TODO uncomment below to create an instance of PreMarketV1ListingRequest
            //instance = new PreMarketV1ListingRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreMarketV1ListingRequest
        /// </summary>
        [Fact]
        public void PreMarketV1ListingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreMarketV1ListingRequest
            //Assert.IsType<PreMarketV1ListingRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ListingStatus'
        /// </summary>
        [Fact]
        public void ListingStatusTest()
        {
            // TODO unit test for the property 'ListingStatus'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DomainAgencyId'
        /// </summary>
        [Fact]
        public void DomainAgencyIdTest()
        {
            // TODO unit test for the property 'DomainAgencyId'
        }
        /// <summary>
        /// Test the property 'ListingProvider'
        /// </summary>
        [Fact]
        public void ListingProviderTest()
        {
            // TODO unit test for the property 'ListingProvider'
        }
        /// <summary>
        /// Test the property 'ProviderAdId'
        /// </summary>
        [Fact]
        public void ProviderAdIdTest()
        {
            // TODO unit test for the property 'ProviderAdId'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Fact]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'Bedrooms'
        /// </summary>
        [Fact]
        public void BedroomsTest()
        {
            // TODO unit test for the property 'Bedrooms'
        }
        /// <summary>
        /// Test the property 'Bathrooms'
        /// </summary>
        [Fact]
        public void BathroomsTest()
        {
            // TODO unit test for the property 'Bathrooms'
        }
        /// <summary>
        /// Test the property 'Carspaces'
        /// </summary>
        [Fact]
        public void CarspacesTest()
        {
            // TODO unit test for the property 'Carspaces'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AuthorityExecutedDate'
        /// </summary>
        [Fact]
        public void AuthorityExecutedDateTest()
        {
            // TODO unit test for the property 'AuthorityExecutedDate'
        }
        /// <summary>
        /// Test the property 'ReservePrice'
        /// </summary>
        [Fact]
        public void ReservePriceTest()
        {
            // TODO unit test for the property 'ReservePrice'
        }
        /// <summary>
        /// Test the property 'EstimatedSalePrice'
        /// </summary>
        [Fact]
        public void EstimatedSalePriceTest()
        {
            // TODO unit test for the property 'EstimatedSalePrice'
        }
        /// <summary>
        /// Test the property 'PropertyTypes'
        /// </summary>
        [Fact]
        public void PropertyTypesTest()
        {
            // TODO unit test for the property 'PropertyTypes'
        }
        /// <summary>
        /// Test the property 'AuthorityType'
        /// </summary>
        [Fact]
        public void AuthorityTypeTest()
        {
            // TODO unit test for the property 'AuthorityType'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodDays'
        /// </summary>
        [Fact]
        public void ExclusivePeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusivePeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusiveContinuingPeriodDays'
        /// </summary>
        [Fact]
        public void ExclusiveContinuingPeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusiveContinuingPeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodStartDate'
        /// </summary>
        [Fact]
        public void ExclusivePeriodStartDateTest()
        {
            // TODO unit test for the property 'ExclusivePeriodStartDate'
        }
        /// <summary>
        /// Test the property 'ActionDate'
        /// </summary>
        [Fact]
        public void ActionDateTest()
        {
            // TODO unit test for the property 'ActionDate'
        }
        /// <summary>
        /// Test the property 'StatementOfInformation'
        /// </summary>
        [Fact]
        public void StatementOfInformationTest()
        {
            // TODO unit test for the property 'StatementOfInformation'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
