/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainSearchServiceV2ModelDomainSearchContractsV2AdvertiserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser
        //private DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser instance;

        public DomainSearchServiceV2ModelDomainSearchContractsV2AdvertiserTests()
        {
            // TODO uncomment below to create an instance of DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser
            //instance = new DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser
        /// </summary>
        [Fact]
        public void DomainSearchServiceV2ModelDomainSearchContractsV2AdvertiserInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser
            //Assert.IsType<DomainSearchServiceV2ModelDomainSearchContractsV2Advertiser>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }
        /// <summary>
        /// Test the property 'PreferredColourHex'
        /// </summary>
        [Fact]
        public void PreferredColourHexTest()
        {
            // TODO unit test for the property 'PreferredColourHex'
        }
        /// <summary>
        /// Test the property 'BannerUrl'
        /// </summary>
        [Fact]
        public void BannerUrlTest()
        {
            // TODO unit test for the property 'BannerUrl'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Fact]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }

    }

}
