/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel
        //private DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel instance;

        public DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModelTests()
        {
            // TODO uncomment below to create an instance of DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel
            //instance = new DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel
        /// </summary>
        [Fact]
        public void DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel
            //Assert.IsType<DomainAPMServiceV2ModelAPMAPIModelsDisclaimerV2DisclaimerModel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Imageurl'
        /// </summary>
        [Fact]
        public void ImageurlTest()
        {
            // TODO unit test for the property 'Imageurl'
        }
        /// <summary>
        /// Test the property 'Authorityname'
        /// </summary>
        [Fact]
        public void AuthoritynameTest()
        {
            // TODO unit test for the property 'Authorityname'
        }

    }

}
