/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainAgencyServiceV2ModelEmailPhone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainAgencyServiceV2ModelEmailPhoneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainAgencyServiceV2ModelEmailPhone
        //private DomainAgencyServiceV2ModelEmailPhone instance;

        public DomainAgencyServiceV2ModelEmailPhoneTests()
        {
            // TODO uncomment below to create an instance of DomainAgencyServiceV2ModelEmailPhone
            //instance = new DomainAgencyServiceV2ModelEmailPhone();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainAgencyServiceV2ModelEmailPhone
        /// </summary>
        [Fact]
        public void DomainAgencyServiceV2ModelEmailPhoneInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainAgencyServiceV2ModelEmailPhone
            //Assert.IsType<DomainAgencyServiceV2ModelEmailPhone>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

    }

}
