/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainPublicAdapterWebApiModelsV1ListingsCommercialContact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainPublicAdapterWebApiModelsV1ListingsCommercialContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainPublicAdapterWebApiModelsV1ListingsCommercialContact
        //private DomainPublicAdapterWebApiModelsV1ListingsCommercialContact instance;

        public DomainPublicAdapterWebApiModelsV1ListingsCommercialContactTests()
        {
            // TODO uncomment below to create an instance of DomainPublicAdapterWebApiModelsV1ListingsCommercialContact
            //instance = new DomainPublicAdapterWebApiModelsV1ListingsCommercialContact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainPublicAdapterWebApiModelsV1ListingsCommercialContact
        /// </summary>
        [Fact]
        public void DomainPublicAdapterWebApiModelsV1ListingsCommercialContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainPublicAdapterWebApiModelsV1ListingsCommercialContact
            //Assert.IsType<DomainPublicAdapterWebApiModelsV1ListingsCommercialContact>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'DisplayFullName'
        /// </summary>
        [Fact]
        public void DisplayFullNameTest()
        {
            // TODO unit test for the property 'DisplayFullName'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
