/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainAgencyServiceV2ModelAgencySummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainAgencyServiceV2ModelAgencySummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainAgencyServiceV2ModelAgencySummary
        //private DomainAgencyServiceV2ModelAgencySummary instance;

        public DomainAgencyServiceV2ModelAgencySummaryTests()
        {
            // TODO uncomment below to create an instance of DomainAgencyServiceV2ModelAgencySummary
            //instance = new DomainAgencyServiceV2ModelAgencySummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainAgencyServiceV2ModelAgencySummary
        /// </summary>
        [Fact]
        public void DomainAgencyServiceV2ModelAgencySummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainAgencyServiceV2ModelAgencySummary
            //Assert.IsType<DomainAgencyServiceV2ModelAgencySummary>(instance);
        }


        /// <summary>
        /// Test the property 'InSuburb'
        /// </summary>
        [Fact]
        public void InSuburbTest()
        {
            // TODO unit test for the property 'InSuburb'
        }
        /// <summary>
        /// Test the property 'QuerySuburb'
        /// </summary>
        [Fact]
        public void QuerySuburbTest()
        {
            // TODO unit test for the property 'QuerySuburb'
        }
        /// <summary>
        /// Test the property 'HasRecentlySold'
        /// </summary>
        [Fact]
        public void HasRecentlySoldTest()
        {
            // TODO unit test for the property 'HasRecentlySold'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Fact]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }
        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Fact]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'Address1'
        /// </summary>
        [Fact]
        public void Address1Test()
        {
            // TODO unit test for the property 'Address1'
        }
        /// <summary>
        /// Test the property 'Address2'
        /// </summary>
        [Fact]
        public void Address2Test()
        {
            // TODO unit test for the property 'Address2'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'RentalTelephone'
        /// </summary>
        [Fact]
        public void RentalTelephoneTest()
        {
            // TODO unit test for the property 'RentalTelephone'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Fact]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'RentalEmail'
        /// </summary>
        [Fact]
        public void RentalEmailTest()
        {
            // TODO unit test for the property 'RentalEmail'
        }
        /// <summary>
        /// Test the property 'HomePageSearchOptions'
        /// </summary>
        [Fact]
        public void HomePageSearchOptionsTest()
        {
            // TODO unit test for the property 'HomePageSearchOptions'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'NumberForSale'
        /// </summary>
        [Fact]
        public void NumberForSaleTest()
        {
            // TODO unit test for the property 'NumberForSale'
        }
        /// <summary>
        /// Test the property 'NumberForRent'
        /// </summary>
        [Fact]
        public void NumberForRentTest()
        {
            // TODO unit test for the property 'NumberForRent'
        }
        /// <summary>
        /// Test the property 'DomainUrl'
        /// </summary>
        [Fact]
        public void DomainUrlTest()
        {
            // TODO unit test for the property 'DomainUrl'
        }
        /// <summary>
        /// Test the property 'ShowTabSoldLastYear'
        /// </summary>
        [Fact]
        public void ShowTabSoldLastYearTest()
        {
            // TODO unit test for the property 'ShowTabSoldLastYear'
        }

    }

}
