/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainAgentSearchV1ModelAutoSuggestAgentResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainAgentSearchV1ModelAutoSuggestAgentResultDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainAgentSearchV1ModelAutoSuggestAgentResultDto
        //private DomainAgentSearchV1ModelAutoSuggestAgentResultDto instance;

        public DomainAgentSearchV1ModelAutoSuggestAgentResultDtoTests()
        {
            // TODO uncomment below to create an instance of DomainAgentSearchV1ModelAutoSuggestAgentResultDto
            //instance = new DomainAgentSearchV1ModelAutoSuggestAgentResultDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainAgentSearchV1ModelAutoSuggestAgentResultDto
        /// </summary>
        [Fact]
        public void DomainAgentSearchV1ModelAutoSuggestAgentResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainAgentSearchV1ModelAutoSuggestAgentResultDto
            //Assert.IsType<DomainAgentSearchV1ModelAutoSuggestAgentResultDto>(instance);
        }


        /// <summary>
        /// Test the property 'AgentId'
        /// </summary>
        [Fact]
        public void AgentIdTest()
        {
            // TODO unit test for the property 'AgentId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AgencyName'
        /// </summary>
        [Fact]
        public void AgencyNameTest()
        {
            // TODO unit test for the property 'AgencyName'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Fact]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ProfileUrl'
        /// </summary>
        [Fact]
        public void ProfileUrlTest()
        {
            // TODO unit test for the property 'ProfileUrl'
        }
        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Fact]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }

    }

}
