/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement
        //private DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement instance;

        public DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElementTests()
        {
            // TODO uncomment below to create an instance of DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement
            //instance = new DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement
        /// </summary>
        [Fact]
        public void DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElementInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement
            //Assert.IsType<DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsCustomSortElement>(instance);
        }


        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }
        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }

    }

}
