/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainSearchServiceV2ModelDomainSearchContractsV2AuctionScheduleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule
        //private DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule instance;

        public DomainSearchServiceV2ModelDomainSearchContractsV2AuctionScheduleTests()
        {
            // TODO uncomment below to create an instance of DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule
            //instance = new DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule
        /// </summary>
        [Fact]
        public void DomainSearchServiceV2ModelDomainSearchContractsV2AuctionScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule
            //Assert.IsType<DomainSearchServiceV2ModelDomainSearchContractsV2AuctionSchedule>(instance);
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'AuctionLocation'
        /// </summary>
        [Fact]
        public void AuctionLocationTest()
        {
            // TODO unit test for the property 'AuctionLocation'
        }

    }

}
