/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListingsV1Objective
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingsV1ObjectiveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingsV1Objective
        //private ListingsV1Objective instance;

        public ListingsV1ObjectiveTests()
        {
            // TODO uncomment below to create an instance of ListingsV1Objective
            //instance = new ListingsV1Objective();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingsV1Objective
        /// </summary>
        [Fact]
        public void ListingsV1ObjectiveInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingsV1Objective
            //Assert.IsType<ListingsV1Objective>(instance);
        }



    }

}
