/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Client.Api;
using Domain.Api.V1.Client.Model;
using Domain.Api.V1.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListingsV2Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingsV2ProjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingsV2Project
        //private ListingsV2Project instance;

        public ListingsV2ProjectTests()
        {
            // TODO uncomment below to create an instance of ListingsV2Project
            //instance = new ListingsV2Project();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingsV2Project
        /// </summary>
        [Fact]
        public void ListingsV2ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingsV2Project
            //Assert.IsType<ListingsV2Project>(instance);
        }


        /// <summary>
        /// Test the property 'ProjectProfileType'
        /// </summary>
        [Fact]
        public void ProjectProfileTypeTest()
        {
            // TODO unit test for the property 'ProjectProfileType'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ViewingAddress'
        /// </summary>
        [Fact]
        public void ViewingAddressTest()
        {
            // TODO unit test for the property 'ViewingAddress'
        }
        /// <summary>
        /// Test the property 'PropertyTypes'
        /// </summary>
        [Fact]
        public void PropertyTypesTest()
        {
            // TODO unit test for the property 'PropertyTypes'
        }
        /// <summary>
        /// Test the property 'DisplayableAddress'
        /// </summary>
        [Fact]
        public void DisplayableAddressTest()
        {
            // TODO unit test for the property 'DisplayableAddress'
        }
        /// <summary>
        /// Test the property 'EnquiryEmailAddress'
        /// </summary>
        [Fact]
        public void EnquiryEmailAddressTest()
        {
            // TODO unit test for the property 'EnquiryEmailAddress'
        }
        /// <summary>
        /// Test the property 'AdvertiserIdentifiers'
        /// </summary>
        [Fact]
        public void AdvertiserIdentifiersTest()
        {
            // TODO unit test for the property 'AdvertiserIdentifiers'
        }
        /// <summary>
        /// Test the property 'ProviderDetails'
        /// </summary>
        [Fact]
        public void ProviderDetailsTest()
        {
            // TODO unit test for the property 'ProviderDetails'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Fact]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'ProjectUrl'
        /// </summary>
        [Fact]
        public void ProjectUrlTest()
        {
            // TODO unit test for the property 'ProjectUrl'
        }
        /// <summary>
        /// Test the property 'Headline'
        /// </summary>
        [Fact]
        public void HeadlineTest()
        {
            // TODO unit test for the property 'Headline'
        }
        /// <summary>
        /// Test the property 'Tagline'
        /// </summary>
        [Fact]
        public void TaglineTest()
        {
            // TODO unit test for the property 'Tagline'
        }
        /// <summary>
        /// Test the property 'DisplayAsLastUpdated'
        /// </summary>
        [Fact]
        public void DisplayAsLastUpdatedTest()
        {
            // TODO unit test for the property 'DisplayAsLastUpdated'
        }
        /// <summary>
        /// Test the property 'ModifiedBy'
        /// </summary>
        [Fact]
        public void ModifiedByTest()
        {
            // TODO unit test for the property 'ModifiedBy'
        }
        /// <summary>
        /// Test the property 'ModifiedDate'
        /// </summary>
        [Fact]
        public void ModifiedDateTest()
        {
            // TODO unit test for the property 'ModifiedDate'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'BackgroundColour'
        /// </summary>
        [Fact]
        public void BackgroundColourTest()
        {
            // TODO unit test for the property 'BackgroundColour'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AppointmentRequired'
        /// </summary>
        [Fact]
        public void AppointmentRequiredTest()
        {
            // TODO unit test for the property 'AppointmentRequired'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'PriceFrom'
        /// </summary>
        [Fact]
        public void PriceFromTest()
        {
            // TODO unit test for the property 'PriceFrom'
        }
        /// <summary>
        /// Test the property 'PriceTo'
        /// </summary>
        [Fact]
        public void PriceToTest()
        {
            // TODO unit test for the property 'PriceTo'
        }
        /// <summary>
        /// Test the property 'BannerUrl'
        /// </summary>
        [Fact]
        public void BannerUrlTest()
        {
            // TODO unit test for the property 'BannerUrl'
        }
        /// <summary>
        /// Test the property 'BigBannerUrl'
        /// </summary>
        [Fact]
        public void BigBannerUrlTest()
        {
            // TODO unit test for the property 'BigBannerUrl'
        }
        /// <summary>
        /// Test the property 'SmallBannerUrl'
        /// </summary>
        [Fact]
        public void SmallBannerUrlTest()
        {
            // TODO unit test for the property 'SmallBannerUrl'
        }
        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }
        /// <summary>
        /// Test the property 'Pdfs'
        /// </summary>
        [Fact]
        public void PdfsTest()
        {
            // TODO unit test for the property 'Pdfs'
        }
        /// <summary>
        /// Test the property 'InspectionDetails'
        /// </summary>
        [Fact]
        public void InspectionDetailsTest()
        {
            // TODO unit test for the property 'InspectionDetails'
        }
        /// <summary>
        /// Test the property 'NumberOfFloors'
        /// </summary>
        [Fact]
        public void NumberOfFloorsTest()
        {
            // TODO unit test for the property 'NumberOfFloors'
        }
        /// <summary>
        /// Test the property 'NumberOfApartments'
        /// </summary>
        [Fact]
        public void NumberOfApartmentsTest()
        {
            // TODO unit test for the property 'NumberOfApartments'
        }
        /// <summary>
        /// Test the property 'EstimatedCompletionDate'
        /// </summary>
        [Fact]
        public void EstimatedCompletionDateTest()
        {
            // TODO unit test for the property 'EstimatedCompletionDate'
        }
        /// <summary>
        /// Test the property 'StartingPrice'
        /// </summary>
        [Fact]
        public void StartingPriceTest()
        {
            // TODO unit test for the property 'StartingPrice'
        }
        /// <summary>
        /// Test the property 'ChildListingIds'
        /// </summary>
        [Fact]
        public void ChildListingIdsTest()
        {
            // TODO unit test for the property 'ChildListingIds'
        }
        /// <summary>
        /// Test the property 'LinkedProjectIds'
        /// </summary>
        [Fact]
        public void LinkedProjectIdsTest()
        {
            // TODO unit test for the property 'LinkedProjectIds'
        }

    }

}
