/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Api;
using Domain.Api.V2.Model;
using Domain.Api.V2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Test.Model
{
    /// <summary>
    ///  Class for testing ListingAdminV2CommercialOffMarketListing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingAdminV2CommercialOffMarketListingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2CommercialOffMarketListing
        //private ListingAdminV2CommercialOffMarketListing instance;

        public ListingAdminV2CommercialOffMarketListingTests()
        {
            // TODO uncomment below to create an instance of ListingAdminV2CommercialOffMarketListing
            //instance = new ListingAdminV2CommercialOffMarketListing();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingAdminV2CommercialOffMarketListing
        /// </summary>
        [Fact]
        public void ListingAdminV2CommercialOffMarketListingInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingAdminV2CommercialOffMarketListing
            //Assert.IsType<ListingAdminV2CommercialOffMarketListing>(instance);
        }


        /// <summary>
        /// Test the property 'UnitsOffered'
        /// </summary>
        [Fact]
        public void UnitsOfferedTest()
        {
            // TODO unit test for the property 'UnitsOffered'
        }
        /// <summary>
        /// Test the property 'UnitDetails'
        /// </summary>
        [Fact]
        public void UnitDetailsTest()
        {
            // TODO unit test for the property 'UnitDetails'
        }
        /// <summary>
        /// Test the property 'AnnualReturn'
        /// </summary>
        [Fact]
        public void AnnualReturnTest()
        {
            // TODO unit test for the property 'AnnualReturn'
        }
        /// <summary>
        /// Test the property 'Nabers'
        /// </summary>
        [Fact]
        public void NabersTest()
        {
            // TODO unit test for the property 'Nabers'
        }
        /// <summary>
        /// Test the property 'Highlights'
        /// </summary>
        [Fact]
        public void HighlightsTest()
        {
            // TODO unit test for the property 'Highlights'
        }
        /// <summary>
        /// Test the property 'DomainAdId'
        /// </summary>
        [Fact]
        public void DomainAdIdTest()
        {
            // TODO unit test for the property 'DomainAdId'
        }
        /// <summary>
        /// Test the property 'InspectionDetails'
        /// </summary>
        [Fact]
        public void InspectionDetailsTest()
        {
            // TODO unit test for the property 'InspectionDetails'
        }
        /// <summary>
        /// Test the property 'IsRural'
        /// </summary>
        [Fact]
        public void IsRuralTest()
        {
            // TODO unit test for the property 'IsRural'
        }
        /// <summary>
        /// Test the property 'ListingProvider'
        /// </summary>
        [Fact]
        public void ListingProviderTest()
        {
            // TODO unit test for the property 'ListingProvider'
        }
        /// <summary>
        /// Test the property 'DomainAgencyID'
        /// </summary>
        [Fact]
        public void DomainAgencyIDTest()
        {
            // TODO unit test for the property 'DomainAgencyID'
        }
        /// <summary>
        /// Test the property 'ProviderAdId'
        /// </summary>
        [Fact]
        public void ProviderAdIdTest()
        {
            // TODO unit test for the property 'ProviderAdId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Fact]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'ListingAction'
        /// </summary>
        [Fact]
        public void ListingActionTest()
        {
            // TODO unit test for the property 'ListingAction'
        }
        /// <summary>
        /// Test the property 'OffMarketDetails'
        /// </summary>
        [Fact]
        public void OffMarketDetailsTest()
        {
            // TODO unit test for the property 'OffMarketDetails'
        }
        /// <summary>
        /// Test the property 'PropertyDetails'
        /// </summary>
        [Fact]
        public void PropertyDetailsTest()
        {
            // TODO unit test for the property 'PropertyDetails'
        }

    }

}
