/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Api;
using Domain.Api.V2.Model;
using Domain.Api.V2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Test.Model
{
    /// <summary>
    ///  Class for testing ListingAdminV2ParkingDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingAdminV2ParkingDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2ParkingDetails
        //private ListingAdminV2ParkingDetails instance;

        public ListingAdminV2ParkingDetailsTests()
        {
            // TODO uncomment below to create an instance of ListingAdminV2ParkingDetails
            //instance = new ListingAdminV2ParkingDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingAdminV2ParkingDetails
        /// </summary>
        [Fact]
        public void ListingAdminV2ParkingDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingAdminV2ParkingDetails
            //Assert.IsType<ListingAdminV2ParkingDetails>(instance);
        }


        /// <summary>
        /// Test the property 'ParkingType'
        /// </summary>
        [Fact]
        public void ParkingTypeTest()
        {
            // TODO unit test for the property 'ParkingType'
        }
        /// <summary>
        /// Test the property 'NumberOfSpaces'
        /// </summary>
        [Fact]
        public void NumberOfSpacesTest()
        {
            // TODO unit test for the property 'NumberOfSpaces'
        }

    }

}
