/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Api;
using Domain.Api.V2.Model;
using Domain.Api.V2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Test.Model
{
    /// <summary>
    ///  Class for testing PreMarketV1ResourceType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PreMarketV1ResourceTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PreMarketV1ResourceType
        //private PreMarketV1ResourceType instance;

        public PreMarketV1ResourceTypeTests()
        {
            // TODO uncomment below to create an instance of PreMarketV1ResourceType
            //instance = new PreMarketV1ResourceType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PreMarketV1ResourceType
        /// </summary>
        [Fact]
        public void PreMarketV1ResourceTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PreMarketV1ResourceType
            //Assert.IsType<PreMarketV1ResourceType>(instance);
        }



    }

}
