/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V2.Api;
using Domain.Api.V2.Model;
using Domain.Api.V2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V2.Test.Model
{
    /// <summary>
    ///  Class for testing SuburbPerformanceStatisticsV3SuburbSeriesInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SuburbPerformanceStatisticsV3SuburbSeriesInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SuburbPerformanceStatisticsV3SuburbSeriesInfo
        //private SuburbPerformanceStatisticsV3SuburbSeriesInfo instance;

        public SuburbPerformanceStatisticsV3SuburbSeriesInfoTests()
        {
            // TODO uncomment below to create an instance of SuburbPerformanceStatisticsV3SuburbSeriesInfo
            //instance = new SuburbPerformanceStatisticsV3SuburbSeriesInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SuburbPerformanceStatisticsV3SuburbSeriesInfo
        /// </summary>
        [Fact]
        public void SuburbPerformanceStatisticsV3SuburbSeriesInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SuburbPerformanceStatisticsV3SuburbSeriesInfo
            //Assert.IsType<SuburbPerformanceStatisticsV3SuburbSeriesInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }

    }

}
