/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Domain.Api.V1.Client;
using Domain.Api.V1.Api;
// uncomment below to import models
//using Domain.Api.V1.Model;

namespace Domain.Api.V1.Test.Api
{
    /// <summary>
    ///  Class for testing AddressLocatorsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AddressLocatorsApiTests : IDisposable
    {
        private AddressLocatorsApi instance;

        public AddressLocatorsApiTests()
        {
            instance = new AddressLocatorsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressLocatorsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AddressLocatorsApi
            //Assert.IsType<AddressLocatorsApi>(instance);
        }

        /// <summary>
        /// Test AddressLocatorsGet
        /// </summary>
        [Fact]
        public void AddressLocatorsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchLevel = null;
            //string unitNumber = null;
            //string streetNumber = null;
            //string streetName = null;
            //string streetType = null;
            //string suburb = null;
            //string state = null;
            //string postcode = null;
            //var response = instance.AddressLocatorsGet(searchLevel, unitNumber, streetNumber, streetName, streetType, suburb, state, postcode);
            //Assert.IsType<List<DomainAPMServiceV3ModelAPMAPIModelsTokenisedSearchV3AddressDataModel>>(response);
        }
    }
}
