/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Domain.Api.V2.Client.OpenAPIDateConverter;

namespace Domain.Api.V2.Model
{
    /// <summary>
    /// Information for past property sales
    /// </summary>
    [DataContract(Name = "Listings.V2.PastSaleData")]
    public partial class ListingsV2PastSaleData : IEquatable<ListingsV2PastSaleData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingsV2PastSaleData" /> class.
        /// </summary>
        /// <param name="unitNumber">Property unit number.</param>
        /// <param name="streetNumber">Property street number.</param>
        /// <param name="street">Property Street name.</param>
        /// <param name="suburb">Property suburb name.</param>
        /// <param name="postcode">Property postcode.</param>
        /// <param name="state">Property state.</param>
        /// <param name="dateOfSale">Registered date of the sale.</param>
        /// <param name="soldPrice">Property sold price.</param>
        public ListingsV2PastSaleData(string unitNumber = default(string), string streetNumber = default(string), string street = default(string), string suburb = default(string), string postcode = default(string), string state = default(string), string dateOfSale = default(string), long soldPrice = default(long))
        {
            this.UnitNumber = unitNumber;
            this.StreetNumber = streetNumber;
            this.Street = street;
            this.Suburb = suburb;
            this.Postcode = postcode;
            this.State = state;
            this.DateOfSale = dateOfSale;
            this.SoldPrice = soldPrice;
        }

        /// <summary>
        /// Property unit number
        /// </summary>
        /// <value>Property unit number</value>
        [DataMember(Name = "unitNumber", EmitDefaultValue = true)]
        public string UnitNumber { get; set; }

        /// <summary>
        /// Property street number
        /// </summary>
        /// <value>Property street number</value>
        [DataMember(Name = "streetNumber", EmitDefaultValue = true)]
        public string StreetNumber { get; set; }

        /// <summary>
        /// Property Street name
        /// </summary>
        /// <value>Property Street name</value>
        [DataMember(Name = "street", EmitDefaultValue = true)]
        public string Street { get; set; }

        /// <summary>
        /// Property suburb name
        /// </summary>
        /// <value>Property suburb name</value>
        [DataMember(Name = "suburb", EmitDefaultValue = true)]
        public string Suburb { get; set; }

        /// <summary>
        /// Property postcode
        /// </summary>
        /// <value>Property postcode</value>
        [DataMember(Name = "postcode", EmitDefaultValue = true)]
        public string Postcode { get; set; }

        /// <summary>
        /// Property state
        /// </summary>
        /// <value>Property state</value>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// display formatted address
        /// </summary>
        /// <value>display formatted address</value>
        [DataMember(Name = "displayAddress", EmitDefaultValue = true)]
        public string DisplayAddress { get; private set; }

        /// <summary>
        /// Returns false as DisplayAddress should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDisplayAddress()
        {
            return false;
        }

        /// <summary>
        /// Registered date of the sale
        /// </summary>
        /// <value>Registered date of the sale</value>
        [DataMember(Name = "dateOfSale", EmitDefaultValue = true)]
        public string DateOfSale { get; set; }

        /// <summary>
        /// Property sold price
        /// </summary>
        /// <value>Property sold price</value>
        [DataMember(Name = "soldPrice", EmitDefaultValue = false)]
        public long SoldPrice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListingsV2PastSaleData {\n");
            sb.Append("  UnitNumber: ").Append(UnitNumber).Append("\n");
            sb.Append("  StreetNumber: ").Append(StreetNumber).Append("\n");
            sb.Append("  Street: ").Append(Street).Append("\n");
            sb.Append("  Suburb: ").Append(Suburb).Append("\n");
            sb.Append("  Postcode: ").Append(Postcode).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  DisplayAddress: ").Append(DisplayAddress).Append("\n");
            sb.Append("  DateOfSale: ").Append(DateOfSale).Append("\n");
            sb.Append("  SoldPrice: ").Append(SoldPrice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListingsV2PastSaleData);
        }

        /// <summary>
        /// Returns true if ListingsV2PastSaleData instances are equal
        /// </summary>
        /// <param name="input">Instance of ListingsV2PastSaleData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListingsV2PastSaleData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UnitNumber == input.UnitNumber ||
                    (this.UnitNumber != null &&
                    this.UnitNumber.Equals(input.UnitNumber))
                ) && 
                (
                    this.StreetNumber == input.StreetNumber ||
                    (this.StreetNumber != null &&
                    this.StreetNumber.Equals(input.StreetNumber))
                ) && 
                (
                    this.Street == input.Street ||
                    (this.Street != null &&
                    this.Street.Equals(input.Street))
                ) && 
                (
                    this.Suburb == input.Suburb ||
                    (this.Suburb != null &&
                    this.Suburb.Equals(input.Suburb))
                ) && 
                (
                    this.Postcode == input.Postcode ||
                    (this.Postcode != null &&
                    this.Postcode.Equals(input.Postcode))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.DisplayAddress == input.DisplayAddress ||
                    (this.DisplayAddress != null &&
                    this.DisplayAddress.Equals(input.DisplayAddress))
                ) && 
                (
                    this.DateOfSale == input.DateOfSale ||
                    (this.DateOfSale != null &&
                    this.DateOfSale.Equals(input.DateOfSale))
                ) && 
                (
                    this.SoldPrice == input.SoldPrice ||
                    this.SoldPrice.Equals(input.SoldPrice)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UnitNumber != null)
                    hashCode = hashCode * 59 + this.UnitNumber.GetHashCode();
                if (this.StreetNumber != null)
                    hashCode = hashCode * 59 + this.StreetNumber.GetHashCode();
                if (this.Street != null)
                    hashCode = hashCode * 59 + this.Street.GetHashCode();
                if (this.Suburb != null)
                    hashCode = hashCode * 59 + this.Suburb.GetHashCode();
                if (this.Postcode != null)
                    hashCode = hashCode * 59 + this.Postcode.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.DisplayAddress != null)
                    hashCode = hashCode * 59 + this.DisplayAddress.GetHashCode();
                if (this.DateOfSale != null)
                    hashCode = hashCode * 59 + this.DateOfSale.GetHashCode();
                hashCode = hashCode * 59 + this.SoldPrice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
