/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Domain.Api.V2.Client.OpenAPIDateConverter;

namespace Domain.Api.V2.Model
{
    /// <summary>
    /// APMAPIModelsSuburbV2SeriesHeaderModel
    /// </summary>
    [DataContract(Name = "SuburbPerformanceStatistics.V3.SuburbSeriesHeader")]
    public partial class SuburbPerformanceStatisticsV3SuburbSeriesHeader : IEquatable<SuburbPerformanceStatisticsV3SuburbSeriesHeader>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SuburbPerformanceStatisticsV3SuburbSeriesHeader" /> class.
        /// </summary>
        /// <param name="suburb">Gets or Sets Suburb.</param>
        /// <param name="state">Gets or Sets State.</param>
        /// <param name="propertyCategory">Gets or Sets PropertyCategory.</param>
        public SuburbPerformanceStatisticsV3SuburbSeriesHeader(string suburb = default(string), string state = default(string), string propertyCategory = default(string))
        {
            this.Suburb = suburb;
            this.State = state;
            this.PropertyCategory = propertyCategory;
        }

        /// <summary>
        /// Gets or Sets Suburb
        /// </summary>
        /// <value>Gets or Sets Suburb</value>
        [DataMember(Name = "suburb", EmitDefaultValue = true)]
        public string Suburb { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        /// <value>Gets or Sets State</value>
        [DataMember(Name = "state", EmitDefaultValue = true)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets PropertyCategory
        /// </summary>
        /// <value>Gets or Sets PropertyCategory</value>
        [DataMember(Name = "propertyCategory", EmitDefaultValue = true)]
        public string PropertyCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SuburbPerformanceStatisticsV3SuburbSeriesHeader {\n");
            sb.Append("  Suburb: ").Append(Suburb).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  PropertyCategory: ").Append(PropertyCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SuburbPerformanceStatisticsV3SuburbSeriesHeader);
        }

        /// <summary>
        /// Returns true if SuburbPerformanceStatisticsV3SuburbSeriesHeader instances are equal
        /// </summary>
        /// <param name="input">Instance of SuburbPerformanceStatisticsV3SuburbSeriesHeader to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SuburbPerformanceStatisticsV3SuburbSeriesHeader input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Suburb == input.Suburb ||
                    (this.Suburb != null &&
                    this.Suburb.Equals(input.Suburb))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.PropertyCategory == input.PropertyCategory ||
                    (this.PropertyCategory != null &&
                    this.PropertyCategory.Equals(input.PropertyCategory))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Suburb != null)
                    hashCode = hashCode * 59 + this.Suburb.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.PropertyCategory != null)
                    hashCode = hashCode * 59 + this.PropertyCategory.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
