/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
        //private DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon instance;

        public DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygonTests()
        {
            // TODO uncomment below to create an instance of DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
            //instance = new DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
        /// </summary>
        [Fact]
        public void DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygonInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon
            //Assert.IsType<DomainSearchServiceV2ModelDomainSearchWebApiV2ModelsPolygon>(instance);
        }


        /// <summary>
        /// Test the property 'Points'
        /// </summary>
        [Fact]
        public void PointsTest()
        {
            // TODO unit test for the property 'Points'
        }

    }

}
