/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData
        //private DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData instance;

        public DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceDataTests()
        {
            // TODO uncomment below to create an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData
            //instance = new DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData
        /// </summary>
        [Fact]
        public void DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData
            //Assert.IsType<DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingMedianPriceData>(instance);
        }


        /// <summary>
        /// Test the property 'PriceType'
        /// </summary>
        [Fact]
        public void PriceTypeTest()
        {
            // TODO unit test for the property 'PriceType'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Fact]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'MedianPrice'
        /// </summary>
        [Fact]
        public void MedianPriceTest()
        {
            // TODO unit test for the property 'MedianPrice'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'SourceDateFrom'
        /// </summary>
        [Fact]
        public void SourceDateFromTest()
        {
            // TODO unit test for the property 'SourceDateFrom'
        }
        /// <summary>
        /// Test the property 'SourceDateTo'
        /// </summary>
        [Fact]
        public void SourceDateToTest()
        {
            // TODO unit test for the property 'SourceDateTo'
        }
        /// <summary>
        /// Test the property 'SourceCollectionDate'
        /// </summary>
        [Fact]
        public void SourceCollectionDateTest()
        {
            // TODO unit test for the property 'SourceCollectionDate'
        }

    }

}
