/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData
        //private DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData instance;

        public DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableDataTests()
        {
            // TODO uncomment below to create an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData
            //instance = new DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData
        /// </summary>
        [Fact]
        public void DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData
            //Assert.IsType<DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingComparableData>(instance);
        }


        /// <summary>
        /// Test the property 'ComparableProperty'
        /// </summary>
        [Fact]
        public void ComparablePropertyTest()
        {
            // TODO unit test for the property 'ComparableProperty'
        }
        /// <summary>
        /// Test the property 'DeclarationText'
        /// </summary>
        [Fact]
        public void DeclarationTextTest()
        {
            // TODO unit test for the property 'DeclarationText'
        }

    }

}
