/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainPublicAdapterWebApiModelsV1ListingsListingLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainPublicAdapterWebApiModelsV1ListingsListingLocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainPublicAdapterWebApiModelsV1ListingsListingLocation
        //private DomainPublicAdapterWebApiModelsV1ListingsListingLocation instance;

        public DomainPublicAdapterWebApiModelsV1ListingsListingLocationTests()
        {
            // TODO uncomment below to create an instance of DomainPublicAdapterWebApiModelsV1ListingsListingLocation
            //instance = new DomainPublicAdapterWebApiModelsV1ListingsListingLocation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainPublicAdapterWebApiModelsV1ListingsListingLocation
        /// </summary>
        [Fact]
        public void DomainPublicAdapterWebApiModelsV1ListingsListingLocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainPublicAdapterWebApiModelsV1ListingsListingLocation
            //Assert.IsType<DomainPublicAdapterWebApiModelsV1ListingsListingLocation>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Fact]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Fact]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
