/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary
        //private DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary instance;

        public DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundaryTests()
        {
            // TODO uncomment below to create an instance of DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary
            //instance = new DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary
        /// </summary>
        [Fact]
        public void DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary
            //Assert.IsType<DomainPublicAdapterWebApiModelsV1PropertiesActivityBoundary>(instance);
        }


        /// <summary>
        /// Test the property 'ListingId'
        /// </summary>
        [Fact]
        public void ListingIdTest()
        {
            // TODO unit test for the property 'ListingId'
        }
        /// <summary>
        /// Test the property 'AdvertisedDate'
        /// </summary>
        [Fact]
        public void AdvertisedDateTest()
        {
            // TODO unit test for the property 'AdvertisedDate'
        }
        /// <summary>
        /// Test the property 'AdvertisedPrice'
        /// </summary>
        [Fact]
        public void AdvertisedPriceTest()
        {
            // TODO unit test for the property 'AdvertisedPrice'
        }
        /// <summary>
        /// Test the property 'Agency'
        /// </summary>
        [Fact]
        public void AgencyTest()
        {
            // TODO unit test for the property 'Agency'
        }
        /// <summary>
        /// Test the property 'AgencyColour'
        /// </summary>
        [Fact]
        public void AgencyColourTest()
        {
            // TODO unit test for the property 'AgencyColour'
        }
        /// <summary>
        /// Test the property 'AgencyId'
        /// </summary>
        [Fact]
        public void AgencyIdTest()
        {
            // TODO unit test for the property 'AgencyId'
        }
        /// <summary>
        /// Test the property 'AgencyLogo'
        /// </summary>
        [Fact]
        public void AgencyLogoTest()
        {
            // TODO unit test for the property 'AgencyLogo'
        }
        /// <summary>
        /// Test the property 'AgencyUrl'
        /// </summary>
        [Fact]
        public void AgencyUrlTest()
        {
            // TODO unit test for the property 'AgencyUrl'
        }
        /// <summary>
        /// Test the property 'ApmAgencyId'
        /// </summary>
        [Fact]
        public void ApmAgencyIdTest()
        {
            // TODO unit test for the property 'ApmAgencyId'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'SuppressDetails'
        /// </summary>
        [Fact]
        public void SuppressDetailsTest()
        {
            // TODO unit test for the property 'SuppressDetails'
        }
        /// <summary>
        /// Test the property 'SuppressPrice'
        /// </summary>
        [Fact]
        public void SuppressPriceTest()
        {
            // TODO unit test for the property 'SuppressPrice'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
