/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails
        //private DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails instance;

        public DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetailsTests()
        {
            // TODO uncomment below to create an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails
            //instance = new DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails
        /// </summary>
        [Fact]
        public void DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails
            //Assert.IsType<DomainListingsServiceV1ModelDomainListingsApiModelQueryResultsListingProviderDetails>(instance);
        }


        /// <summary>
        /// Test the property 'ProviderSystem'
        /// </summary>
        [Fact]
        public void ProviderSystemTest()
        {
            // TODO unit test for the property 'ProviderSystem'
        }
        /// <summary>
        /// Test the property 'ProviderAdID'
        /// </summary>
        [Fact]
        public void ProviderAdIDTest()
        {
            // TODO unit test for the property 'ProviderAdID'
        }

    }

}
