/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainListingAdminServiceV1ModelInspection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainListingAdminServiceV1ModelInspectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainListingAdminServiceV1ModelInspection
        //private DomainListingAdminServiceV1ModelInspection instance;

        public DomainListingAdminServiceV1ModelInspectionTests()
        {
            // TODO uncomment below to create an instance of DomainListingAdminServiceV1ModelInspection
            //instance = new DomainListingAdminServiceV1ModelInspection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainListingAdminServiceV1ModelInspection
        /// </summary>
        [Fact]
        public void DomainListingAdminServiceV1ModelInspectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainListingAdminServiceV1ModelInspection
            //Assert.IsType<DomainListingAdminServiceV1ModelInspection>(instance);
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Repeat'
        /// </summary>
        [Fact]
        public void RepeatTest()
        {
            // TODO unit test for the property 'Repeat'
        }

    }

}
