/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.V1.Api;
using Domain.Api.V1.Model;
using Domain.Api.V1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.V1.Test.Model
{
    /// <summary>
    ///  Class for testing DomainListingAdminServiceV1ModelPastSaleData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainListingAdminServiceV1ModelPastSaleDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainListingAdminServiceV1ModelPastSaleData
        //private DomainListingAdminServiceV1ModelPastSaleData instance;

        public DomainListingAdminServiceV1ModelPastSaleDataTests()
        {
            // TODO uncomment below to create an instance of DomainListingAdminServiceV1ModelPastSaleData
            //instance = new DomainListingAdminServiceV1ModelPastSaleData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainListingAdminServiceV1ModelPastSaleData
        /// </summary>
        [Fact]
        public void DomainListingAdminServiceV1ModelPastSaleDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainListingAdminServiceV1ModelPastSaleData
            //Assert.IsType<DomainListingAdminServiceV1ModelPastSaleData>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DateOfSale'
        /// </summary>
        [Fact]
        public void DateOfSaleTest()
        {
            // TODO unit test for the property 'DateOfSale'
        }
        /// <summary>
        /// Test the property 'SoldPrice'
        /// </summary>
        [Fact]
        public void SoldPriceTest()
        {
            // TODO unit test for the property 'SoldPrice'
        }

    }

}
