/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api.Client.Api;
using Domain.Api.Client.Model;
using Domain.Api.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ListingAdminV2ParkingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListingAdminV2ParkingInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2ParkingInfo
        //private ListingAdminV2ParkingInfo instance;

        public ListingAdminV2ParkingInfoTests()
        {
            // TODO uncomment below to create an instance of ListingAdminV2ParkingInfo
            //instance = new ListingAdminV2ParkingInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListingAdminV2ParkingInfo
        /// </summary>
        [Fact]
        public void ListingAdminV2ParkingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListingAdminV2ParkingInfo
            //Assert.IsType<ListingAdminV2ParkingInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'Information'
        /// </summary>
        [Fact]
        public void InformationTest()
        {
            // TODO unit test for the property 'Information'
        }

    }

}
