/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Domain.Api.V1.Client.OpenAPIDateConverter;

namespace Domain.Api.V1.Model
{
    /// <summary>
    /// DomainSearchServiceV2ModelDomainSearchContractsV2Inspection
    /// </summary>
    [DataContract(Name = "Domain.SearchService.v2.Model.DomainSearchContractsV2Inspection")]
    public partial class DomainSearchServiceV2ModelDomainSearchContractsV2Inspection : IEquatable<DomainSearchServiceV2ModelDomainSearchContractsV2Inspection>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainSearchServiceV2ModelDomainSearchContractsV2Inspection" /> class.
        /// </summary>
        /// <param name="openingTime">openingTime.</param>
        /// <param name="closingTime">closingTime.</param>
        public DomainSearchServiceV2ModelDomainSearchContractsV2Inspection(DateTime openingTime = default(DateTime), DateTime closingTime = default(DateTime))
        {
            this.OpeningTime = openingTime;
            this.ClosingTime = closingTime;
        }

        /// <summary>
        /// Gets or Sets OpeningTime
        /// </summary>
        [DataMember(Name = "openingTime", EmitDefaultValue = false)]
        public DateTime OpeningTime { get; set; }

        /// <summary>
        /// Gets or Sets ClosingTime
        /// </summary>
        [DataMember(Name = "closingTime", EmitDefaultValue = false)]
        public DateTime ClosingTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DomainSearchServiceV2ModelDomainSearchContractsV2Inspection {\n");
            sb.Append("  OpeningTime: ").Append(OpeningTime).Append("\n");
            sb.Append("  ClosingTime: ").Append(ClosingTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DomainSearchServiceV2ModelDomainSearchContractsV2Inspection);
        }

        /// <summary>
        /// Returns true if DomainSearchServiceV2ModelDomainSearchContractsV2Inspection instances are equal
        /// </summary>
        /// <param name="input">Instance of DomainSearchServiceV2ModelDomainSearchContractsV2Inspection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DomainSearchServiceV2ModelDomainSearchContractsV2Inspection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OpeningTime == input.OpeningTime ||
                    (this.OpeningTime != null &&
                    this.OpeningTime.Equals(input.OpeningTime))
                ) && 
                (
                    this.ClosingTime == input.ClosingTime ||
                    (this.ClosingTime != null &&
                    this.ClosingTime.Equals(input.ClosingTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OpeningTime != null)
                    hashCode = hashCode * 59 + this.OpeningTime.GetHashCode();
                if (this.ClosingTime != null)
                    hashCode = hashCode * 59 + this.ClosingTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
