/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Domain.Api.V1.Client.OpenAPIDateConverter;

namespace Domain.Api.V1.Model
{
    /// <summary>
    /// Statement of Information  Regarding sale listing
    /// </summary>
    [DataContract(Name = "Domain.ListingAdminService.v1.Model.StatementOfInformation")]
    public partial class DomainListingAdminServiceV1ModelStatementOfInformation : IEquatable<DomainListingAdminServiceV1ModelStatementOfInformation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DomainListingAdminServiceV1ModelStatementOfInformation" /> class.
        /// </summary>
        /// <param name="estimatedPrice">estimatedPrice.</param>
        /// <param name="comparableData">comparableData.</param>
        /// <param name="suburbMedianPrice">suburbMedianPrice.</param>
        /// <param name="documentationUrl">Link to the statement of information documentation file.  Must be a PDF file.  File should be less than 10 MB in size  The Statement of Information must be updated if there is a change in the indicative selling price..</param>
        public DomainListingAdminServiceV1ModelStatementOfInformation(DomainListingAdminServiceV1ModelBasicPrice estimatedPrice = default(DomainListingAdminServiceV1ModelBasicPrice), DomainListingAdminServiceV1ModelComparableData comparableData = default(DomainListingAdminServiceV1ModelComparableData), DomainListingAdminServiceV1ModelMedianPriceData suburbMedianPrice = default(DomainListingAdminServiceV1ModelMedianPriceData), string documentationUrl = default(string))
        {
            this.EstimatedPrice = estimatedPrice;
            this.ComparableData = comparableData;
            this.SuburbMedianPrice = suburbMedianPrice;
            this.DocumentationUrl = documentationUrl;
        }

        /// <summary>
        /// Gets or Sets EstimatedPrice
        /// </summary>
        [DataMember(Name = "estimatedPrice", EmitDefaultValue = false)]
        public DomainListingAdminServiceV1ModelBasicPrice EstimatedPrice { get; set; }

        /// <summary>
        /// Gets or Sets ComparableData
        /// </summary>
        [DataMember(Name = "comparableData", EmitDefaultValue = false)]
        public DomainListingAdminServiceV1ModelComparableData ComparableData { get; set; }

        /// <summary>
        /// Gets or Sets SuburbMedianPrice
        /// </summary>
        [DataMember(Name = "suburbMedianPrice", EmitDefaultValue = false)]
        public DomainListingAdminServiceV1ModelMedianPriceData SuburbMedianPrice { get; set; }

        /// <summary>
        /// Link to the statement of information documentation file.  Must be a PDF file.  File should be less than 10 MB in size  The Statement of Information must be updated if there is a change in the indicative selling price.
        /// </summary>
        /// <value>Link to the statement of information documentation file.  Must be a PDF file.  File should be less than 10 MB in size  The Statement of Information must be updated if there is a change in the indicative selling price.</value>
        [DataMember(Name = "documentationUrl", EmitDefaultValue = false)]
        public string DocumentationUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DomainListingAdminServiceV1ModelStatementOfInformation {\n");
            sb.Append("  EstimatedPrice: ").Append(EstimatedPrice).Append("\n");
            sb.Append("  ComparableData: ").Append(ComparableData).Append("\n");
            sb.Append("  SuburbMedianPrice: ").Append(SuburbMedianPrice).Append("\n");
            sb.Append("  DocumentationUrl: ").Append(DocumentationUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DomainListingAdminServiceV1ModelStatementOfInformation);
        }

        /// <summary>
        /// Returns true if DomainListingAdminServiceV1ModelStatementOfInformation instances are equal
        /// </summary>
        /// <param name="input">Instance of DomainListingAdminServiceV1ModelStatementOfInformation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DomainListingAdminServiceV1ModelStatementOfInformation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EstimatedPrice == input.EstimatedPrice ||
                    (this.EstimatedPrice != null &&
                    this.EstimatedPrice.Equals(input.EstimatedPrice))
                ) && 
                (
                    this.ComparableData == input.ComparableData ||
                    (this.ComparableData != null &&
                    this.ComparableData.Equals(input.ComparableData))
                ) && 
                (
                    this.SuburbMedianPrice == input.SuburbMedianPrice ||
                    (this.SuburbMedianPrice != null &&
                    this.SuburbMedianPrice.Equals(input.SuburbMedianPrice))
                ) && 
                (
                    this.DocumentationUrl == input.DocumentationUrl ||
                    (this.DocumentationUrl != null &&
                    this.DocumentationUrl.Equals(input.DocumentationUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EstimatedPrice != null)
                    hashCode = hashCode * 59 + this.EstimatedPrice.GetHashCode();
                if (this.ComparableData != null)
                    hashCode = hashCode * 59 + this.ComparableData.GetHashCode();
                if (this.SuburbMedianPrice != null)
                    hashCode = hashCode * 59 + this.SuburbMedianPrice.GetHashCode();
                if (this.DocumentationUrl != null)
                    hashCode = hashCode * 59 + this.DocumentationUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
