/*
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * The version of the OpenAPI document: v1
 * Contact: api@domain.com.au
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Domain.Api.V1.Client;
using Domain.Api.V1.Model;

namespace Domain.Api.V1.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a subscription
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <returns>DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription WebhooksCreateSubscription(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest);

        /// <summary>
        /// Creates a subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <returns>ApiResponse of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksCreateSubscriptionWithHttpInfo(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest);
        /// <summary>
        /// Deletes a webhook subscription
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns></returns>
        void WebhooksDeleteSubscription(string id);

        /// <summary>
        /// Deletes a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> WebhooksDeleteSubscriptionWithHttpInfo(string id);
        /// <summary>
        /// Retrieves a webhook subscription
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription WebhooksGetSubscription(string id);

        /// <summary>
        /// Retrieves a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>ApiResponse of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksGetSubscriptionWithHttpInfo(string id);
        /// <summary>
        /// Retreives all webhook subscriptions
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksListSubscriptions(string id, int? pageNumber = default(int?), int? pageSize = default(int?));

        /// <summary>
        /// Retreives all webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>ApiResponse of List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksListSubscriptionsWithHttpInfo(string id, int? pageNumber = default(int?), int? pageSize = default(int?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Creates a subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        System.Threading.Tasks.Task<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksCreateSubscriptionAsync(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Creates a subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksCreateSubscriptionWithHttpInfoAsync(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Deletes a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task WebhooksDeleteSubscriptionAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Deletes a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> WebhooksDeleteSubscriptionWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieves a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        System.Threading.Tasks.Task<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksGetSubscriptionAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves a webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksGetSubscriptionWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retreives all webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        System.Threading.Tasks.Task<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksListSubscriptionsAsync(string id, int? pageNumber = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retreives all webhook subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>>> WebhooksListSubscriptionsWithHttpInfoAsync(string id, int? pageNumber = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhooksApi : IWebhooksApiSync, IWebhooksApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebhooksApi : IWebhooksApi
    {
        private Domain.Api.V1.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi(String basePath)
        {
            this.Configuration = Domain.Api.V1.Client.Configuration.MergeConfigurations(
                Domain.Api.V1.Client.GlobalConfiguration.Instance,
                new Domain.Api.V1.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Domain.Api.V1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Domain.Api.V1.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Domain.Api.V1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WebhooksApi(Domain.Api.V1.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Domain.Api.V1.Client.Configuration.MergeConfigurations(
                Domain.Api.V1.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Domain.Api.V1.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Domain.Api.V1.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Domain.Api.V1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WebhooksApi(Domain.Api.V1.Client.ISynchronousClient client, Domain.Api.V1.Client.IAsynchronousClient asyncClient, Domain.Api.V1.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Domain.Api.V1.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Domain.Api.V1.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Domain.Api.V1.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Domain.Api.V1.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Domain.Api.V1.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Creates a subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <returns>DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription WebhooksCreateSubscription(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest)
        {
            Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> localVarResponse = WebhooksCreateSubscriptionWithHttpInfo(id, domainNotificationPortalV1ModelAddSubscriptionRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <returns>ApiResponse of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksCreateSubscriptionWithHttpInfo(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksCreateSubscription");

            // verify the required parameter 'domainNotificationPortalV1ModelAddSubscriptionRequest' is set
            if (domainNotificationPortalV1ModelAddSubscriptionRequest == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'domainNotificationPortalV1ModelAddSubscriptionRequest' when calling WebhooksApi->WebhooksCreateSubscription");

            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "text/json",
                "text/html",
                "application/xml",
                "text/xml",
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html"
            };

            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = domainNotificationPortalV1ModelAddSubscriptionRequest;

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>("/v1/webhooks/{id}/subscriptions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksCreateSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates a subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public async System.Threading.Tasks.Task<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksCreateSubscriptionAsync(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> localVarResponse = await WebhooksCreateSubscriptionWithHttpInfoAsync(id, domainNotificationPortalV1ModelAddSubscriptionRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Webhook identifier</param>
        /// <param name="domainNotificationPortalV1ModelAddSubscriptionRequest">Subscription data</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription)</returns>
        public async System.Threading.Tasks.Task<Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksCreateSubscriptionWithHttpInfoAsync(string id, DomainNotificationPortalV1ModelAddSubscriptionRequest domainNotificationPortalV1ModelAddSubscriptionRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksCreateSubscription");

            // verify the required parameter 'domainNotificationPortalV1ModelAddSubscriptionRequest' is set
            if (domainNotificationPortalV1ModelAddSubscriptionRequest == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'domainNotificationPortalV1ModelAddSubscriptionRequest' when calling WebhooksApi->WebhooksCreateSubscription");


            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "text/json", 
                "text/html", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html"
            };


            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = domainNotificationPortalV1ModelAddSubscriptionRequest;

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>("/v1/webhooks/{id}/subscriptions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksCreateSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns></returns>
        public void WebhooksDeleteSubscription(string id)
        {
            WebhooksDeleteSubscriptionWithHttpInfo(id);
        }

        /// <summary>
        /// Deletes a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Domain.Api.V1.Client.ApiResponse<Object> WebhooksDeleteSubscriptionWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksDeleteSubscription");

            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
            };

            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/v1/subscriptions/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksDeleteSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deletes a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task WebhooksDeleteSubscriptionAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await WebhooksDeleteSubscriptionWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Deletes a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Domain.Api.V1.Client.ApiResponse<Object>> WebhooksDeleteSubscriptionWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksDeleteSubscription");


            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
            };


            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/v1/subscriptions/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksDeleteSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription WebhooksGetSubscription(string id)
        {
            Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> localVarResponse = WebhooksGetSubscriptionWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <returns>ApiResponse of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksGetSubscriptionWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksGetSubscription");

            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html"
            };

            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>("/v1/subscriptions/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksGetSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription</returns>
        public async System.Threading.Tasks.Task<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksGetSubscriptionAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> localVarResponse = await WebhooksGetSubscriptionWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a webhook subscription 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscription identifier</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription)</returns>
        public async System.Threading.Tasks.Task<Domain.Api.V1.Client.ApiResponse<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksGetSubscriptionWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksGetSubscription");


            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html"
            };


            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>("/v1/subscriptions/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksGetSubscription", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retreives all webhook subscriptions 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        public List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription> WebhooksListSubscriptions(string id, int? pageNumber = default(int?), int? pageSize = default(int?))
        {
            Domain.Api.V1.Client.ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> localVarResponse = WebhooksListSubscriptionsWithHttpInfo(id, pageNumber, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retreives all webhook subscriptions 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <returns>ApiResponse of List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        public Domain.Api.V1.Client.ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksListSubscriptionsWithHttpInfo(string id, int? pageNumber = default(int?), int? pageSize = default(int?))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksListSubscriptions");

            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html",
                "application/xml",
                "text/xml"
            };

            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (pageNumber != null)
            {
                localVarRequestOptions.QueryParameters.Add(Domain.Api.V1.Client.ClientUtils.ParameterToMultiMap("", "pageNumber", pageNumber));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Domain.Api.V1.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>>("/v1/webhooks/{id}/subscriptions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksListSubscriptions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retreives all webhook subscriptions 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;</returns>
        public async System.Threading.Tasks.Task<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> WebhooksListSubscriptionsAsync(string id, int? pageNumber = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Domain.Api.V1.Client.ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>> localVarResponse = await WebhooksListSubscriptionsWithHttpInfoAsync(id, pageNumber, pageSize, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retreives all webhook subscriptions 
        /// </summary>
        /// <exception cref="Domain.Api.V1.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Subscriber (Webhook) ID</param>
        /// <param name="pageNumber"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription&gt;)</returns>
        public async System.Threading.Tasks.Task<Domain.Api.V1.Client.ApiResponse<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>>> WebhooksListSubscriptionsWithHttpInfoAsync(string id, int? pageNumber = default(int?), int? pageSize = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new Domain.Api.V1.Client.ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->WebhooksListSubscriptions");


            Domain.Api.V1.Client.RequestOptions localVarRequestOptions = new Domain.Api.V1.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "text/json",
                "text/html",
                "application/xml",
                "text/xml"
            };


            var localVarContentType = Domain.Api.V1.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Domain.Api.V1.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", Domain.Api.V1.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (pageNumber != null)
            {
                localVarRequestOptions.QueryParameters.Add(Domain.Api.V1.Client.ClientUtils.ParameterToMultiMap("", "pageNumber", pageNumber));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Domain.Api.V1.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            // authentication (apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }
            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<DomainPublicAdapterWebApiModelsV1SubscriptionsSubscription>>("/v1/webhooks/{id}/subscriptions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WebhooksListSubscriptions", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
